// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handlers/auth.go

// Package mock_handlers is a generated GoMock package.
package mock_handlers

import (
	reflect "reflect"
	adapters "websocket-confee/internal/adapters"

	gomock "github.com/golang/mock/gomock"
)

// MockredisServiceInterface is a mock of redisServiceInterface interface.
type MockredisServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockredisServiceInterfaceMockRecorder
}

// MockredisServiceInterfaceMockRecorder is the mock recorder for MockredisServiceInterface.
type MockredisServiceInterfaceMockRecorder struct {
	mock *MockredisServiceInterface
}

// NewMockredisServiceInterface creates a new mock instance.
func NewMockredisServiceInterface(ctrl *gomock.Controller) *MockredisServiceInterface {
	mock := &MockredisServiceInterface{ctrl: ctrl}
	mock.recorder = &MockredisServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockredisServiceInterface) EXPECT() *MockredisServiceInterfaceMockRecorder {
	return m.recorder
}

// HGet mocks base method.
func (m *MockredisServiceInterface) HGet(key, field string) adapters.StringCmdInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HGet", key, field)
	ret0, _ := ret[0].(adapters.StringCmdInterface)
	return ret0
}

// HGet indicates an expected call of HGet.
func (mr *MockredisServiceInterfaceMockRecorder) HGet(key, field interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HGet", reflect.TypeOf((*MockredisServiceInterface)(nil).HGet), key, field)
}

// Publish mocks base method.
func (m *MockredisServiceInterface) Publish(message interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockredisServiceInterfaceMockRecorder) Publish(message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockredisServiceInterface)(nil).Publish), message)
}
